### ISSUE TITLE
packets libs fields.lua has changed

### ISSUE THREAD

**Issue by Ivaar** [Tny5989/Valkyrie#3]
I found this recently and just wanted to pass along that Outgoing 0x05C _unknown3 field was recently changed to _unknown2 and Rotation.

**Comment by Tny5989** [comment]
Thank you for the update.  I just recently reactivated so I might try to update some of my old projects.

**Comment by Tny5989** [comment]
Should be fixed. fc44b3e50bfe7d3dcb1a1f1e4006317579ad061e
